#!/usr/bin/env python3
"""
Test function coverage functionality in PyDCov.

This test verifies that function coverage is properly collected and displayed
in coverage reports generated by PyDCov.
"""

import pytest
import subprocess
import tempfile
import shutil
import os
import re
from pathlib import Path


class TestFunctionCoverage:
    """Test function coverage collection and reporting."""

    @pytest.mark.slow
    def test_function_coverage_in_reports(self):
        """Test that function coverage is included in generated reports."""
        # Skip if coverage tools are not available
        if not self._check_coverage_tools():
            pytest.skip("Coverage tools (gcov/lcov/genhtml) not available")

        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)
            
            # Copy the algorithm example to temp directory
            example_src = Path(__file__).parent.parent / 'examples' / 'algorithm'
            project_path = temp_path / 'algorithm_test'
            shutil.copytree(example_src, project_path)
            
            # Build the project with coverage
            build_dir = project_path / 'build'
            build_dir.mkdir(exist_ok=True)
            
            # Configure with coverage enabled
            env = os.environ.copy()
            env['PYDCOV_ENABLE_COVERAGE'] = '1'
            
            cmake_result = subprocess.run([
                'cmake', '..', '-DCMAKE_BUILD_TYPE=Debug'
            ], cwd=build_dir, capture_output=True, text=True, env=env)
            
            if cmake_result.returncode != 0:
                pytest.skip(f"CMake configuration failed: {cmake_result.stderr}")
            
            # Build the project
            make_result = subprocess.run([
                'make'
            ], cwd=build_dir, capture_output=True, text=True)
            
            if make_result.returncode != 0:
                pytest.skip(f"Build failed: {make_result.stderr}")
            
            # Initialize PyDCov
            init_result = subprocess.run([
                'pydcov', 'init', '--build-root', str(build_dir)
            ], cwd=project_path, capture_output=True, text=True)
            
            assert init_result.returncode == 0, f"PyDCov init failed: {init_result.stderr}"
            
            # Run tests to generate coverage data
            add_result = subprocess.run([
                'pydcov', 'add', 'python', '-m', 'pytest', 'tests/', '-v'
            ], cwd=project_path, capture_output=True, text=True)
            
            assert add_result.returncode == 0, f"PyDCov add failed: {add_result.stderr}"
            
            # Merge coverage data
            merge_result = subprocess.run([
                'pydcov', 'merge'
            ], cwd=project_path, capture_output=True, text=True)
            
            assert merge_result.returncode == 0, f"PyDCov merge failed: {merge_result.stderr}"
            
            # Generate coverage report
            report_result = subprocess.run([
                'pydcov', 'report'
            ], cwd=project_path, capture_output=True, text=True)
            
            assert report_result.returncode == 0, f"PyDCov report failed: {report_result.stderr}"
            
            # Check that function coverage is included in the report
            self._verify_function_coverage_in_reports(build_dir)

    def _check_coverage_tools(self) -> bool:
        """Check if required coverage tools are available."""
        tools = ['gcov', 'lcov', 'genhtml']
        for tool in tools:
            result = subprocess.run(['which', tool], capture_output=True)
            if result.returncode != 0:
                return False
        return True

    def _verify_function_coverage_in_reports(self, build_dir: Path):
        """Verify that function coverage is present in generated reports."""
        # Check for pydcov directory
        pydcov_dirs = list(build_dir.glob('pydcov_*'))
        assert len(pydcov_dirs) > 0, "No pydcov directory found"
        
        pydcov_dir = pydcov_dirs[0]  # Use the first (and likely only) pydcov directory
        
        # Check for merged.info file
        merged_info = pydcov_dir / 'merged.info'
        assert merged_info.exists(), f"merged.info not found in {pydcov_dir}"
        
        # Read and check merged.info content for function coverage
        info_content = merged_info.read_text()
        
        # Look for function coverage entries (FN, FNDA, FNF, FNH lines)
        function_patterns = [
            r'^FN:\d+,\w+',      # Function definition: FN:line,function_name
            r'^FNDA:\d+,\w+',    # Function data: FNDA:execution_count,function_name
            r'^FNF:\d+',         # Functions found: FNF:count
            r'^FNH:\d+',         # Functions hit: FNH:count
        ]
        
        found_patterns = []
        for pattern in function_patterns:
            if re.search(pattern, info_content, re.MULTILINE):
                found_patterns.append(pattern)
        
        assert len(found_patterns) > 0, f"No function coverage data found in merged.info. Content preview: {info_content[:500]}"
        
        # Check for HTML report
        report_dir = pydcov_dir / 'report'
        assert report_dir.exists(), f"Report directory not found in {pydcov_dir}"
        
        index_html = report_dir / 'index.html'
        assert index_html.exists(), f"index.html not found in {report_dir}"
        
        # Check HTML content for function coverage
        html_content = index_html.read_text()
        
        # Look for function coverage in HTML
        function_html_patterns = [
            r'Function Coverage',
            r'Functions:',
            r'function.*coverage',
            r'FN[FH]',  # Function coverage metrics
        ]
        
        found_html_patterns = []
        for pattern in function_html_patterns:
            if re.search(pattern, html_content, re.IGNORECASE):
                found_html_patterns.append(pattern)
        
        assert len(found_html_patterns) > 0, f"No function coverage found in HTML report. Content preview: {html_content[:1000]}"
        
        print(f"✓ Function coverage verification passed!")
        print(f"  - Found {len(found_patterns)} function coverage patterns in merged.info")
        print(f"  - Found {len(found_html_patterns)} function coverage patterns in HTML report")

    def test_gcov_function_flag(self):
        """Test that gcov is called with the -f flag for function coverage."""
        from pydcov.utils.coverage_file_manager import CoverageFileManager
        from pydcov.utils.path_utils import PathManager
        from unittest.mock import patch, MagicMock
        
        # Create a mock path manager
        with tempfile.TemporaryDirectory() as temp_dir:
            build_dir = Path(temp_dir) / 'build'
            build_dir.mkdir()
            (build_dir / 'CMakeCache.txt').touch()

            pydcov_dir = Path(temp_dir) / 'pydcov_dir'
            pydcov_dir.mkdir()

            file_manager = CoverageFileManager(build_dir, pydcov_dir)
            
            # Mock subprocess.run to capture the gcov command
            with patch('pydcov.utils.coverage_file_manager.subprocess.run') as mock_run:
                mock_run.return_value = MagicMock(returncode=0, stdout='', stderr='')
                
                # Create dummy files
                gcda_file = Path(temp_dir) / 'test.gcda'
                gcno_file = Path(temp_dir) / 'test.gcno'
                working_dir = Path(temp_dir)
                
                gcda_file.touch()
                gcno_file.touch()
                
                # Call the method
                file_manager._process_individual_gcda_file(gcda_file, gcno_file, working_dir)
                
                # Verify gcov was called with -f flag
                assert mock_run.called, "subprocess.run was not called"
                
                # Get the first call arguments
                call_args = mock_run.call_args_list[0]
                gcov_cmd = call_args[0][0]  # First positional argument
                
                assert '-f' in gcov_cmd, f"gcov command missing -f flag: {gcov_cmd}"
                print(f"✓ gcov called with function coverage flag: {gcov_cmd}")


if __name__ == '__main__':
    pytest.main([__file__])
